# Define the Site
site_name: "Project Euler"
repo_url: https://github.com/10jmellott/ProjectEuler

# Define the Site Layout
pages:
- Home: index.md
- Problems:
  - P1 - Multiples of 3 and 5: problems/p001.md
  - P2 - Even Fibonacci Numbers: problems/p002.md
  - P3 - Largest Prime Factor: problems/p003.md
  - P4 - Largest Palindrome Product: problems/p004.md
- Utils:
  - Stopwatch: utils/stopwatch.md
  - Eratosthenes: utils/eratosthenes.md
- Documentation:
  - Main: documentation/__main__.md
  - Document Header: documentation/DocumentDocstring.md
  - Google Docstring: documentation/GoogleDocstring.md
  - Markdown Html Formatter: documentation/HtmlMarkdownBuilder.md

# Define Markdown & HTML Build Options
docs_dir: docs_md
site_dir: docs
theme:    readthedocs

# Define some additional css
extra_css: ["custom.css"]

# Enable the extension to allow inline HTML & Markdown to work (kind-of) seamlessly
markdown_extensions:
- extra
- toc
