# Define the Site
site_name: "Project Euler"
repo_url: https://github.com/10jmellott/ProjectEuler

# Define the Site Layout
pages:
- Home: index.md
- Problems:
  - P1 - Multiples of 3 and 5: problems/p001.md
  - P2 - Even Fibonacci Numbers: problems/p002.md
  - P3 - Largest Prime Factor: problems/p003.md
  - P4 - Largest Palindrome Product: problems/p004.md
  - P5 - Smallest Multiple: problems/p005.md
  - P6 - Sum Square Difference: problems/p006.md
  - P7 - 10001st Prime: problems/p007.md
  - P8 - Largest Product in a Series: problems/p008.md
  - P9 - Special Pythagorean Triplet: problems/p009.md
  - P10 - Summation of Primes: problems/p010.md
  - P11 - Largest Product in a Grid: problems/p011.md
  - P12 - Highly Divisible Triangular Number: problems/p012.md
  - P13 - Large Sum: problems/p013.md
  - P14 - Longest Collatz Sequence: problems/p014.md
  - P15 - Lattice Paths: problems/p015.md
  - P16 - Power Digit Sum: problems/p016.md
  - P17 - Number Letter Counts: problems/p017.md
  - P18 - Maximum Path Sum I: problems/p018.md
  - P19 - Counting Sundays: problems/p019.md
  - P20 - Factorial Digit Sum: problems/p020.md
  - P21 - Amicable Numbers: problems/p021.md
  - P22 - Names Scores: problems/p022.md
  - P23 - Non-Abundant Sums: problems/p023.md
  - P24 - Lexicographic Permutations: problems/p024.md
  - P25 - 1000-Digit Fibonacci Number: problems/p025.md
- Utils:
  - Init: utils/__init__.md
  - Stopwatch: utils/stopwatch.md
  - Eratosthenes: utils/eratosthenes.md
  - Fibonacci: utils/fibonacci.md
  - OEIS: utils/oeis.md
- Documentation:
  - Main: documentation/__main__.md
  - Document Header: documentation/DocumentDocstring.md
  - Google Docstring: documentation/GoogleDocstring.md
  - Markdown Html Formatter: documentation/HtmlMarkdownBuilder.md

# Define Markdown & HTML Build Options
docs_dir: docs_md
site_dir: docs
theme:    readthedocs

# Define some additional css
extra_css: ["custom.css"]

# Enable the extension to allow inline HTML & Markdown to work (kind-of) seamlessly
markdown_extensions:
- extra
- toc
